name: Production workflow - Lambda Function - Prod
on:
  push:
    branches: [main]

jobs:
  Deploy-package-npm-pipeline:
    uses: PePires58/ReusableWorkflows/.github/workflows/001_nodejs_npm_pipeline.yaml@main
    with:
      working-directory: "src"
      execute-unit-tests: "true"
      nome-pacote: "escoladesoftware-autorizador-sdk"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      