name: Production workflow - Lambda Function - Prod
on:
  push:
    branches: [main-ts]

jobs:
  Deploy-package-npm-pipeline:
    uses: PePires58/ReusableWorkflows/.github/workflows/005_typescript_npm_pipeline.yaml@main
    with:
      working-directory: "src"
      execute-unit-tests: "true"
      build-js-directory: "lib"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      